TweetAppが完成しました。
liskis/TweetApp pull request #2
Opened 2023-12-14 02:06 UTC by liskis

### 要件
- ホーム画面
    - ユーザー名表示
    - ツイート表示
    - ツイートに合わせて高さを可変
- ツイート投稿画面
    - ツイートを投稿できる
    - ユーザー名を投稿できる
        - 本物のTwitterだと、アカウント登録するが、サンプルアプリではアカウント登録機能がないので、ユーザー名を投稿する必要がある
    - ツイートは140字以下のみ投稿できる
- データの保存/編集/削除
    - Realm(ローカル)による実装

ワイヤーフレーム
https://drive.google.com/file/d/1P_tw6neizY_yGu-jTUtwcyzLNTSxVa1I/view?usp=sharing

ワイヤーフレームではホーム画面に「編集」と「削除」のボタンを設置する予定でしたが、
「cellをタップ」で編集画面へ
「cellを左ヘスワイプ」で削除ボタンの表示
へ変更しました。

controllerディレクトリ内に
「ContentView.swift」と「UITweetView.swift」がありますが、
使わなくなったのでローカルでは削除したのですが、
github上には残っているようです。

2023-12-14 07:06 UTC, LunaChevalier requested changes
よくできていると思います!
以下の点の修正をお願いします
- 141文字以上入力することができませんでした
    - 「ツイートは140字以下のみ投稿できる」要件の兼ね合いで上記のような実装をしているかと思いますが、漢字変換などでどうしても140文字目あたりで数文字入力しないと入力できない文字が出てきますので、入力制限をせずにこの要件を満たしてください
- 「controllerディレクトリ内に」のところですが、削除されているので、プルリクエストの概要の更新をお願いします
- TweetAppの`Minimum Deployments`を16。0にしてください
    - 今の17.2だと、最新のiOSバージョン以外でアプリがインストールできない状態になっています

2023-12-14 07:06 UTC, LunaChevalier commented on TweetApp/Assets.xcassets/羽ペン.imageset/Contents.json
> +      "filename" : "羽根のペンx2.png",
文字コードなどの兼ね合いで、日本語をファイル名に使うと、特定の文字でファイルと認識されない可能性があるので、アルファベットでお願いします

2023-12-14 07:06 UTC, LunaChevalier commented on TweetApp/Assets.xcassets/羽ペン.imageset/羽根のペンx2.png
文字コードなどの兼ね合いで、日本語をファイル名に使うと、特定の文字でファイルと認識されない可能性があるので、アルファベットでお願いします

2023-12-14 07:42 UTC, liskis commented on TweetApp/Assets.xcassets/羽ペン.imageset/Contents.json
> +      "filename" : "羽根のペンx2.png",
fetherPenに変更しました。

2023-12-14 07:42 UTC, liskis commented on TweetApp/Assets.xcassets/羽ペン.imageset/羽根のペンx2.png
fetherPenに変更しました。

2023-12-14 07:50 UTC, liskis commented
文字入力時は文字数の表示と140文字を超えたときに文字数を赤く表示するのみに変更し
tweetBtnが押された時に140文字を超えているとsaveData()が実行されないように変更しました。

2023-12-14 08:15 UTC, liskis commented
ついでにappIcomも設定しました。

2023-12-15 03:51 UTC, LunaChevalier approved these changes

2023-12-15 03:53 UTC, closed without merging